# 1. Numpy

- 파이썬 라이브러리 중 하나 -> 과학연산
- 배열 -> 행렬 (선형대수)
- 선형대수, 푸리에 변환 -> 수학 함수


In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3,4]) # 1차원 배열 생성

In [9]:
print(a)

[1 2 3 4]


In [10]:
l = [1,2,3,4]
print(l)

[1, 2, 3, 4]


In [11]:
print(a.shape) # 배열 축의 크기

(4,)


In [12]:
print(a.ndim) # 배열의 차원

1


In [13]:
print(a.dtype) # 배열의 데이터 타입

int64


In [14]:
print(a.itemsize) # 각 요소의 바이트 단위 크기

8


In [20]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [21]:
print(b)
print(b.ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

[[1 2]
 [3 4]]
2
int64
8
32


In [23]:
# 3차원
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
int64
8
64


In [24]:
# 하나의 숫자값 : 스칼라

s = np.array(1)
print(s)

1


In [25]:
# 1차원 : 벡터 

v = np.array([1,2,3])
print(v)

[1 2 3]


In [26]:
# 2차원 : 행렬(Matrix)

m = np.array([[1,2,3],[1,2,3]])
print(m)

[[1 2 3]
 [1 2 3]]


In [29]:
# 3차원 : 텐서(Tensor)
t = np.array([[[1,2],[1,2]],[[1,2],[1,2]]])
print(t)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [30]:
# for문을 이용해서 배열 생성

f = np.array([i for i in range(0,10,2)]) #(start, end, step)

In [31]:
print(f)

[0 2 4 6 8]


In [32]:
print(f)
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
1
int64
8
40


## 데이터 타입

### 1. 숫자형
### 2. 문자형
### 3. 논리형

### 숫자형

- 부호가 있는 정수(Signed Integer)
- 부호가 없는 정수(Unsigned Integer)
- 실수(Float)
- 복소수(Complex)

In [33]:
# int( 8bit, 16bit, 32bit, 64bit)

data = [1.1, 2, 3]

i = np.array(data, dtype = np.int32)
print(i)

[1 2 3]


In [35]:
print(i.dtype)

int32


In [36]:
data2 = [-1, 2, 3]

ui = np.array(data2, dtype=np.uint32) # uint 8, 16, 32( ~ 4,294,967,295), 64
print(ui)

[4294967295          2          3]


In [37]:
f = np.array(data, dtype=np.float64)

print(f)

[1.1 2.  3. ]


In [40]:
c = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex64)

In [41]:
print(c.real) # 실수

[1. 3. 5.]


In [43]:
print(c.imag) # 허수

[2. 4. 6.]


## 문자형

- String_
- Unicode_

In [44]:
data = [1, 2, 3]

s = np.string_(data)

In [45]:
print(s)

b'\x01\x02\x03'


In [47]:
print(s.dtype) # S3 : string 3

|S3


In [48]:
data3 = [1, 2, 3, 4, 5]

#string_
s2 = np.string_(data3)

print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


In [50]:
u = np.array(data3, dtype= 'U')
print(u)
print(u.dtype)

['1' '2' '3' '4' '5']
<U1


In [53]:
data4 = [11, 22, 33, 44, 55]

u2 = np.array(data4, dtype = 'U')
print(u2)
print(u2.dtype)

['11' '22' '33' '44' '55']
<U2


## 논리형 (boolean)

- True(1), False(0)
- 비트 연산 사용

In [58]:
l1 = np.array([True, False, True])
l2 = np.array([False, True, False])


print(l1)
print(l2)

[ True False  True]
[False  True False]


In [59]:
and_ = np.logical_and(l1, l2)
print(and_)

[False False False]


## 데이터 형 변환 (Cast, Casting 형 변환)

- 데이터들끼리 형태를 맞춰줌
- 예시) 이미지 데이터 -> uint형으로 불러옴 -> float


In [60]:
data = [1.1, 2, 3]

a = np.float64(data) #np.데이터타입
print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [61]:
a = a.astype(np.int64)
print(a)
print(a.dtype)

[1 2 3]
int64


In [62]:
b = np.uint16(0)

print(b)
print(b.dtype)

0
uint16


In [64]:
b = b - 1

print(b)
print(b.dtype)

-1
int64


In [65]:
c = np.uint16(-1) # uint ( 0 ~ 65,535 )

print(c)

65535


## 산술연산

In [75]:
import time

data = [[1, 2, 3], [4, 5, 6]]
data2 = [[1, 1, 1], [2, 2, 2]]
sum = 0

start_time = time.time()

for i in range(len(data)):
    for j in range(len(data[i])):
        sum += data[i][j]

print(sum)


21


In [76]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 덧셈
sum = a + b

# 뺄셈
min = a - b

# 곱셈
mul = a * b

# 나눗셈
div = a / b

print(sum)
print(min)
print(mul)
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [77]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

aa = np.exp(a)  # 지수함수
print(aa)

[ 2.71828183  7.3890561  20.08553692]


In [80]:
bb = np.log(b) # 자연로그
print(bb)

[1.38629436 1.60943791 1.79175947]


In [81]:
cc = np.log2(b) # 밑이 2인 로그
print(cc)

[2.         2.32192809 2.5849625 ]


In [85]:
d = np.array([0, np.pi/2, np.pi])

sin_ = np.sin(d)

cos_ = np.cos(d)

tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## 배열의 연결과 분할


In [86]:
print("a" + "b")

ab


In [87]:
x = [1, 2, 3]
y = [4, 5, 6]

In [88]:
concat = np.concatenate([x, y])
print(concat)

[1 2 3 4 5 6]


In [89]:
x2 = [[1, 2], [3, 4]]
y2 = [[4, 5], [6, 7]]

concat2 = np.concatenate([x2, y2])
print(concat2)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [90]:
x2 = [[1, 2], [3, 4]]
y2 = [[4, 5], [6, 7]]

concat2 = np.concatenate([x2, y2], axis = 0) # 행 병함
print(concat2)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [92]:
x2 = [[1, 2], [3, 4]]
y2 = [[4, 5], [6, 7]]

concat2 = np.concatenate([x2, y2], axis = 1) # 열 병합
print(concat2)

[[1 2 4 5]
 [3 4 6 7]]


In [93]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [94]:
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [95]:
arr.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [98]:
x2 = [[1, 2], [3, 4]] # 2*2
y2 = [[4, 5], [6, 7]] # 2*2

# hstack horizontal - 수펑
h = np.hstack([x2, y2])
print(h)

[[1 2 4 5]
 [3 4 6 7]]


In [99]:
# vstack vertical - 수직

v = np.vstack([x2, y2])
print(v)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [108]:
x2 = np.array([[1, 2], [3, 4], [5, 6]]) # 2*2

# hsplit

h = np.hsplit(x2, 2)
print(h)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [110]:
# vsplit

v = np.vsplit(x2, 3)
print(v)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


## 다양한 배열 만들기

In [115]:
zero = np.zeros([4,5])
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [111]:
one = np.ones([3, 4])
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [112]:
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy 제공 함수

In [119]:
arr1 = np.array([-1, -2, -3, -4])
abs_arr = np.abs(arr1)

print(abs_arr)

[1 2 3 4]


In [120]:
arr2 = np.array([1, 4, 9, 16, 25])
sqrt_arr = np.sqrt(arr2)

print(sqrt_arr)

[1. 2. 3. 4. 5.]


# 집계함수

In [122]:
a = np.array([1, 2, 3, 4, 5])
a_mean = np.mean(a) # 평균

print(a_mean)

3.0


In [124]:
b = np.array([1, 3, 5, 7, 9])
b_median = np.median(b) # 중앙값

print(b_median)

5.0


In [125]:
c = np.array([1, 2, 3, 4, 5])
c_std = np.std(c) #표준편차

print(c_std)

1.4142135623730951


In [126]:
d = np.array([1, 2, 3, 4, 5])
d_var = np.var(d)  # 분산

print(d_var)

2.0


In [127]:
e = np.array([1, 2, 3, 4, 5])
e_sum = np.sum(e) # 합계

print(e_sum)

15


In [129]:
e_cumsum = np.cumsum(e) # 누적합계

print(e_cumsum)

[ 1  3  6 10 15]


In [131]:
min = np.argmin(e)
print(min) #최소값의 인덱스

0


In [134]:
min = np.min(e)
print(min) #최소값

1


In [135]:
max = np.max(e)
print(max) #최대값

5


In [138]:
max = np.argmax(e)
print(max) #최대값의 인덱스

4


In [139]:
a = np.array([0, 0, 0, 1]) # 배열 안에 하나라도 true가 있는지

a_true = np.any(a)
print(a_true)

True


In [141]:
a_all = np.all(a)
print(a_all)

False


In [142]:
b = np.array([1, 1, 1, 1])

b_all = np.all(b)
print(b_all)

True


In [143]:
# NaN

a = np.array([1, 2, np.nan, 4])
a_nsum = np.nansum(a)

print(a_nsum)

7.0


In [144]:
a_sum = np.sum(a)

print(a_sum)

nan


In [149]:
d = np.array([1, 2, 3, 4, 5])

condition = np.where(d < 3, d, 0) # 조건 true인 경우, false인 경우
condition1 = np.where(d < 3)

print(condition)
print(condition1)

[1 2 0 0 0]
(array([0, 1]),)


## Boolean Indexing

조건에 따른 요소들을 판별해서 새로운 배열을 만든다

In [153]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # 원본 데이터

even_a = a[a % 2 == 0]

print(even_a)
print(a)

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


### Broadcast(브로드캐스트)

- 크기가 다른 배열 간의 연산도 가능하게 해줌
- ex) 1차원, 2차원

In [155]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [157]:
d = np.array([[1], [2], [3]])
e = np.array([4, 5, 6])

f = d + e

In [158]:
print(f)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


- 두 배열의 차원수가 다를 경우, 더 작은 차원의 배열에 큰 차원의 배열이 맞을 때까지 1을 추가한다.

- 두 배열의 차원 수가 같을 경우에도 크기가 1인 차원이 있다면 다른 배열의 크기와 일치하도록 복제된다.

- 두 배열의 차원 수가 같은 경우에도, 모든 차원의 크기가 같거나 크기가 1이라면 모양이 같은 두 배여랴의 요소 간 연산을 한다.

In [159]:
d = np.array([[1], [2], [3]])
e = np.array([[4], [5], [6]])

f = d + e

In [160]:
print(f)

[[5]
 [7]
 [9]]


In [163]:
g = np.array([[1], [2], [3]])
h = np.array([[4, 5, 6]])

f = g + h

In [164]:
print(f)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
